# Generated by Django 4.2.7 on 2026-06-16 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BindingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_code', models.CharField(max_length=50, unique=True, verbose_name='装册计划号')),
                ('target_quantity', models.IntegerField(verbose_name='目标册数')),
                ('planned_date', models.DateField(verbose_name='计划日期')),
                ('operator', models.CharField(max_length=50, verbose_name='负责人')),
                ('remark', models.CharField(blank=True, max_length=300, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '装册计划',
                'verbose_name_plural': '装册计划',
                'ordering': ['-planned_date'],
            },
        ),
        migrations.CreateModel(
            name='PaperBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_no', models.CharField(max_length=50, unique=True, verbose_name='批号')),
                ('quantity', models.IntegerField(verbose_name='纸张数量(张)')),
                ('status', models.CharField(choices=[('pending_press', '待压平'), ('pressing', '压平中'), ('pending_cut', '待裁边'), ('pending_review', '待审核'), ('ready_bind', '可装册'), ('detained', '留置中')], default='pending_press', max_length=20, verbose_name='状态')),
                ('operator', models.CharField(max_length=50, verbose_name='负责人')),
                ('press_start', models.DateTimeField(blank=True, null=True, verbose_name='压平开始时间')),
                ('press_end', models.DateTimeField(blank=True, null=True, verbose_name='压平结束时间')),
                ('warp_count', models.IntegerField(default=0, verbose_name='翘边数')),
                ('warp_note', models.CharField(blank=True, max_length=500, verbose_name='翘边说明')),
                ('break_count', models.IntegerField(default=0, verbose_name='破口数')),
                ('break_detail', models.CharField(blank=True, max_length=500, verbose_name='破口记录详情')),
                ('detain_reason', models.CharField(blank=True, max_length=500, verbose_name='留置原因')),
                ('detained_at', models.DateTimeField(blank=True, null=True, verbose_name='留置时间')),
                ('previous_status', models.CharField(blank=True, choices=[('pending_press', '待压平'), ('pressing', '压平中'), ('pending_cut', '待裁边'), ('pending_review', '待审核'), ('ready_bind', '可装册'), ('detained', '留置中')], max_length=20, null=True)),
                ('reject_reason', models.CharField(blank=True, max_length=500, verbose_name='驳回原因')),
                ('reject_count', models.IntegerField(default=0, verbose_name='驳回次数')),
                ('review_operator', models.CharField(blank=True, max_length=50, verbose_name='审核人')),
                ('review_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('bind_confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='装册确认时间')),
                ('bind_confirmed_by', models.CharField(blank=True, max_length=50, verbose_name='装册确认人')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('binding_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches', to='api.bindingplan', verbose_name='所属装册计划')),
            ],
            options={
                'verbose_name': '纸张批次',
                'verbose_name_plural': '纸张批次',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaperSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='规格名称')),
                ('width', models.IntegerField(verbose_name='宽度(mm)')),
                ('height', models.IntegerField(verbose_name='高度(mm)')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '幅面规格',
                'verbose_name_plural': '幅面规格',
            },
        ),
        migrations.CreateModel(
            name='PressPlate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='板位编号')),
                ('location', models.CharField(max_length=100, verbose_name='存放位置')),
                ('capacity', models.IntegerField(default=100, verbose_name='最大承载量(张)')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '压平板位',
                'verbose_name_plural': '压平板位',
            },
        ),
        migrations.CreateModel(
            name='ReviewRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='规则名称')),
                ('max_warp_count', models.IntegerField(default=2, verbose_name='最大翘边数')),
                ('max_break_count', models.IntegerField(default=3, verbose_name='最大破口数')),
                ('max_press_minutes', models.IntegerField(default=120, verbose_name='最大压平时长(分钟)')),
                ('break_cluster_threshold', models.IntegerField(default=5, verbose_name='同批破口集中阈值')),
                ('pending_review_hours', models.IntegerField(default=24, verbose_name='待审核超时(小时)')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '复核规则',
                'verbose_name_plural': '复核规则',
            },
        ),
        migrations.CreateModel(
            name='StatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(choices=[('pending_press', '待压平'), ('pressing', '压平中'), ('pending_cut', '待裁边'), ('pending_review', '待审核'), ('ready_bind', '可装册'), ('detained', '留置中')], max_length=20, verbose_name='原状态')),
                ('to_status', models.CharField(choices=[('pending_press', '待压平'), ('pressing', '压平中'), ('pending_cut', '待裁边'), ('pending_review', '待审核'), ('ready_bind', '可装册'), ('detained', '留置中')], max_length=20, verbose_name='目标状态')),
                ('operator', models.CharField(max_length=50, verbose_name='操作人')),
                ('remark', models.CharField(blank=True, max_length=500, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_histories', to='api.paperbatch', verbose_name='批次')),
            ],
            options={
                'verbose_name': '状态变更历史',
                'verbose_name_plural': '状态变更历史',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='paperbatch',
            name='plate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='api.pressplate', verbose_name='压平板位'),
        ),
        migrations.AddField(
            model_name='paperbatch',
            name='spec',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='api.paperspec', verbose_name='幅面规格'),
        ),
        migrations.CreateModel(
            name='BreakRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet_no', models.IntegerField(verbose_name='张号')),
                ('position', models.CharField(max_length=100, verbose_name='位置')),
                ('length_mm', models.IntegerField(default=0, verbose_name='长度(mm)')),
                ('operator', models.CharField(max_length=50, verbose_name='记录人')),
                ('remark', models.CharField(blank=True, max_length=300, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='break_records', to='api.paperbatch', verbose_name='批次')),
            ],
            options={
                'verbose_name': '破口记录',
                'verbose_name_plural': '破口记录',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnomalyAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('break_cluster', '同批号破口集中'), ('press_timeout', '压平时间过长'), ('plate_conflict', '板位冲突'), ('review_missing', '审核遗漏')], max_length=30, verbose_name='异常类型')),
                ('message', models.CharField(max_length=500, verbose_name='异常描述')),
                ('extra', models.JSONField(blank=True, default=dict, verbose_name='附加信息')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='是否已处理')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='api.paperbatch', verbose_name='批次')),
            ],
            options={
                'verbose_name': '异常告警',
                'verbose_name_plural': '异常告警',
                'ordering': ['-created_at'],
            },
        ),
    ]
